function convertJsonToJs(jsonData) {
    debugger
    const data = JSON.parse(jsonData);
    const jsCode = data.map(item => {
        const keys = Object.keys(item);
        const formattedItem = keys.map(key => {
            const formattedKey = /^[a-zA-Z]+$/.test(key) ? key : `'${key}'`;
            const formattedValue = typeof item[key] === 'string' ? `'${item[key]}'` : item[key];
            return `${formattedKey}: ${formattedValue}`;
        });
        return `{ ${formattedItem.join(', ')} }`;
    });
    return `const data = [\n  ${jsCode.join(',\n  ')}\n];`;
}

const jsonData = `[
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "OTOMANA LEWA [rys. 002]",
    "LP": 1,
    "NAZWA": "PŁ. BOK",
    "DŁ.": 895,
    "SZER.": 640,
    "GR.": 15,
    "SZT": 1,
    "MATERIAŁ": "PL. WIOROWA",
    "UWAGI": "003"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "OTOMANA LEWA [rys. 002]",
    "LP": 2,
    "NAZWA": "PŁ. TYŁ",
    "DŁ.": 875,
    "SZER.": 640,
    "GR.": 15,
    "SZT": 1,
    "MATERIAŁ": "PL. WIOROWA",
    "UWAGI": "BRW"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "OTOMANA LEWA [rys. 002]",
    "LP": 3,
    "NAZWA": "PŁ. PRZEG. WEW. PRZÓD",
    "DŁ.": 875,
    "SZER.": 640,
    "GR.": 15,
    "SZT": 1,
    "MATERIAŁ": "PL. WIOROWA",
    "UWAGI": "004"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "OTOMANA LEWA [rys. 002]",
    "LP": 4,
    "NAZWA": "PŁ. PRZEG. WEW. TYŁ",
    "DŁ.": 875,
    "SZER.": 617,
    "GR.": 15,
    "SZT": 1,
    "MATERIAŁ": "PL. WIOROWA",
    "UWAGI": "005"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "OTOMANA LEWA [rys. 002]",
    "LP": 5,
    "NAZWA": "PŁ. PRZEG. WEW. ŚR.",
    "DŁ.": 875,
    "SZER.": 617,
    "GR.": 15,
    "SZT": 1,
    "MATERIAŁ": "PL. WIOROWA",
    "UWAGI": "006"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "OTOMANA LEWA [rys. 002]",
    "LP": 6,
    "NAZWA": "PŁ. PRZÓD",
    "DŁ.": 875,
    "SZER.": 280,
    "GR.": 15,
    "SZT": 1,
    "MATERIAŁ": "PL. WIOROWA",
    "UWAGI": "BRW"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "OTOMANA LEWA [rys. 002]",
    "LP": 7,
    "NAZWA": "LIST. WEW.",
    "DŁ.": 1840,
    "SZER.": 50,
    "GR.": 23,
    "SZT": 4,
    "MATERIAŁ": "T-CA SOSNA",
    "UWAGI": "BRW"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "OTOMANA LEWA [rys. 002]",
    "LP": 8,
    "NAZWA": "LIST. OPAR. BOK",
    "DŁ.": 1500,
    "SZER.": 50,
    "GR.": 23,
    "SZT": 3,
    "MATERIAŁ": "T-CA SOSNA",
    "UWAGI": "BRW"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "OTOMANA LEWA [rys. 002]",
    "LP": 9,
    "NAZWA": "LIST. WZMAC.",
    "DŁ.": 875,
    "SZER.": 50,
    "GR.": 23,
    "SZT": 2,
    "MATERIAŁ": "T-CA SOSNA",
    "UWAGI": "BRW"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "OTOMANA LEWA [rys. 002]",
    "LP": 10,
    "NAZWA": "LIST. OPAR.",
    "DŁ.": 725,
    "SZER.": 50,
    "GR.": 23,
    "SZT": 2,
    "MATERIAŁ": "T-CA SOSNA",
    "UWAGI": "BRW"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "OTOMANA LEWA [rys. 002]",
    "LP": 11,
    "NAZWA": "LIST. SIED. TYŁ KR.",
    "DŁ.": 325,
    "SZER.": 50,
    "GR.": 23,
    "SZT": 1,
    "MATERIAŁ": "T-CA SOSNA",
    "UWAGI": "BRW"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "OTOMANA LEWA [rys. 002]",
    "LP": 12,
    "NAZWA": "LIST. NAR. PRZÓD",
    "DŁ.": 150,
    "SZER.": 50,
    "GR.": 23,
    "SZT": 3,
    "MATERIAŁ": "T-CA SOSNA",
    "UWAGI": "BRW"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "OTOMANA LEWA [rys. 002]",
    "LP": 13,
    "NAZWA": "KL. MONT.",
    "DŁ.": 50,
    "SZER.": 50,
    "GR.": 23,
    "SZT": 22,
    "MATERIAŁ": "T-CA SOSNA",
    "UWAGI": "BRW"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "OTOMANA LEWA [rys. 002]",
    "LP": 14,
    "NAZWA": "LIST. SIED. DOL. PRZ.",
    "DŁ.": 775,
    "SZER.": 25,
    "GR.": 25,
    "SZT": 1,
    "MATERIAŁ": "T-CA SOSNA",
    "UWAGI": "BRW"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "OTOMANA LEWA [rys. 002]",
    "LP": 15,
    "NAZWA": "LIST. WEW. SIED. PRZ-TYŁ",
    "DŁ.": 600,
    "SZER.": 25,
    "GR.": 25,
    "SZT": 2,
    "MATERIAŁ": "T-CA SOSNA",
    "UWAGI": "BRW"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "OTOMANA LEWA [rys. 002]",
    "LP": 16,
    "NAZWA": "PŁ. TYŁ OPAR. BOK",
    "DŁ.": 1530,
    "SZER.": 640,
    "GR.": 3,
    "SZT": 1,
    "MATERIAŁ": "PL. HDF",
    "UWAGI": "BRW"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "OTOMANA LEWA [rys. 002]",
    "LP": 17,
    "NAZWA": "PŁ. PRZÓD OPAR. BOK",
    "DŁ.": 1345,
    "SZER.": 300,
    "GR.": 3,
    "SZT": 1,
    "MATERIAŁ": "PL. HDF",
    "UWAGI": "BRW"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "OTOMANA LEWA [rys. 002]",
    "LP": 18,
    "NAZWA": "PŁ. PRZÓD OPAR.",
    "DŁ.": 730,
    "SZER.": 300,
    "GR.": 3,
    "SZT": 1,
    "MATERIAŁ": "PL. HDF",
    "UWAGI": "BRW"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "OTOMANA LEWA [rys. 002]",
    "LP": 19,
    "NAZWA": "PŁ. WEW.",
    "DŁ.": 970,
    "SZER.": 280,
    "GR.": 3,
    "SZT": 1,
    "MATERIAŁ": "PL. HDF",
    "UWAGI": "BRW"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "OTOMANA LEWA [rys. 002]",
    "LP": 20,
    "NAZWA": "PŁ. TYŁ. PRZÓD",
    "DŁ.": 335,
    "SZER.": 280,
    "GR.": 3,
    "SZT": 1,
    "MATERIAŁ": "PL. HDF",
    "UWAGI": "BRW"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "OTOMANA LEWA [rys. 002]",
    "LP": 21,
    "NAZWA": "PŁ. TYŁ OPAR.",
    "DŁ.": 1345,
    "SZER.": 145,
    "GR.": 3,
    "SZT": 1,
    "MATERIAŁ": "PL. HDF",
    "UWAGI": "BRW"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "OTOMANA LEWA [rys. 002]",
    "LP": 22,
    "NAZWA": "PŁ. GÓR. OPAR. BOK",
    "DŁ.": 890,
    "SZER.": 170,
    "GR.": 3,
    "SZT": 1,
    "MATERIAŁ": "PL. HDF",
    "UWAGI": "BRW"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "OTOMANA LEWA [rys. 002]",
    "LP": 23,
    "NAZWA": "TEK. PRZEG. SIED.",
    "DŁ.": 397,
    "SZER.": 40,
    "GR.": 1,
    "SZT": 2,
    "MATERIAŁ": "TEKTURA",
    "UWAGI": "BRW"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "OTOMANA LEWA [rys. 002]",
    "LP": 24,
    "NAZWA": "TAŚMA ZACZEP. 16SZT.",
    "DŁ.": 1600,
    "SZT": 2,
    "MATERIAŁ": "TWORZYWO",
    "UWAGI": "BRW"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "OTOMANA LEWA [rys. 002]",
    "LP": 25,
    "NAZWA": "NAK. KLOWA M6",
    "SZT": 4,
    "MATERIAŁ": "STAL",
    "UWAGI": "BRW"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "2F SKRZYNIA [rys. 007]",
    "LP": 1,
    "NAZWA": "PŁ. PRZÓD",
    "DŁ.": 1308,
    "SZER.": 218,
    "GR.": 16,
    "SZT": 1,
    "MATERIAŁ": "PL. WIOROWA BIALA",
    "UWAGI": "008"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "2F SKRZYNIA [rys. 007]",
    "LP": 2,
    "NAZWA": "PŁ. TYŁ",
    "DŁ.": 1308,
    "SZER.": 218,
    "GR.": 16,
    "SZT": 1,
    "MATERIAŁ": "PL. WIOROWA BIALA",
    "UWAGI": "009"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "2F SKRZYNIA [rys. 007]",
    "LP": 3,
    "NAZWA": "PŁ. BOK",
    "DŁ.": 615,
    "SZER.": 218,
    "GR.": 16,
    "SZT": 2,
    "MATERIAŁ": "PL. MDF BIALA",
    "UWAGI": "010"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "2F SKRZYNIA [rys. 007]",
    "LP": 4,
    "NAZWA": "PŁ. WEW.",
    "DŁ.": 584,
    "SZER.": 50,
    "GR.": 23,
    "SZT": 1,
    "MATERIAŁ": "T-CA SOSNA",
    "UWAGI": "FAZA"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "2F SKRZYNIA [rys. 007]",
    "LP": 5,
    "NAZWA": "LIST. TYŁ",
    "DŁ.": 170,
    "SZER.": 50,
    "GR.": 23,
    "SZT": 2,
    "MATERIAŁ": "T-CA SOSNA",
    "UWAGI": "FAZA"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "2F SKRZYNIA [rys. 007]",
    "LP": 6,
    "NAZWA": "PŁ. BOK DÓŁ",
    "DŁ.": 584,
    "SZER.": 50,
    "GR.": 18,
    "SZT": 2,
    "MATERIAŁ": "SKLEJKA",
    "UWAGI": "FAZA"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "2F SKRZYNIA [rys. 007]",
    "LP": 7,
    "NAZWA": "LIST. TYŁ ŚR.",
    "DŁ.": 195,
    "SZER.": 50,
    "GR.": 18,
    "SZT": 2,
    "MATERIAŁ": "SKLEJKA",
    "UWAGI": "FAZA"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "2F SKRZYNIA [rys. 007]",
    "LP": 8,
    "NAZWA": "PŁ. BOK PRZÓD",
    "DŁ.": 115,
    "SZER.": 50,
    "GR.": 18,
    "SZT": 2,
    "MATERIAŁ": "SKLEJKA",
    "UWAGI": "FAZA"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "2F SKRZYNIA [rys. 007]",
    "LP": 9,
    "NAZWA": "PŁ. DNO",
    "DŁ.": 1337,
    "SZER.": 615,
    "GR.": 3,
    "SZT": 1,
    "MATERIAŁ": "PL. PILSN. BIALA",
    "UWAGI": "011"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "2F SKRZYNIA [rys. 007]",
    "LP": 10,
    "NAZWA": "NAK. KLOWA M6",
    "SZT": 18,
    "MATERIAŁ": "STAL",
    "UWAGI": "BRW"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "2F SKRZYNIA [rys. 007]",
    "LP": 11,
    "NAZWA": "WKRET ST 3x30",
    "SZT": 14,
    "MATERIAŁ": "STAL",
    "UWAGI": "BRW"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "2F OPARCIE [rys. 012]",
    "LP": 1,
    "NAZWA": "PŁ. TYŁ",
    "DŁ.": 1330,
    "SZER.": 640,
    "GR.": 15,
    "SZT": 1,
    "MATERIAŁ": "PL. WIOROWA",
    "UWAGI": "013"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "2F OPARCIE [rys. 012]",
    "LP": 2,
    "NAZWA": "PŁ. GÓRNA",
    "DŁ.": 1330,
    "SZER.": 20,
    "GR.": 6,
    "SZT": 1,
    "MATERIAŁ": "PL. MDF",
    "UWAGI": "BRW"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "2F OPARCIE [rys. 012]",
    "LP": 3,
    "NAZWA": "PŁ. BOK",
    "DŁ.": 620,
    "SZER.": 20,
    "GR.": 6,
    "SZT": 2,
    "MATERIAŁ": "PL. MDF",
    "UWAGI": "BRW"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "2F OPARCIE [rys. 012]",
    "LP": 4,
    "NAZWA": "PŁ. WZMAC.",
    "DŁ.": 210,
    "SZER.": 100,
    "GR.": 6,
    "SZT": 2,
    "MATERIAŁ": "SKLEJKA",
    "UWAGI": "BRW"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "2F OPARCIE [rys. 012]",
    "LP": 5,
    "NAZWA": "NAK. KLOWA M6",
    "SZT": 4,
    "MATERIAŁ": "STAL",
    "UWAGI": "BRW"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "2F RAMA [rys. 014]",
    "LP": 1,
    "NAZWA": "PŁ. PRZÓD",
    "DŁ.": 1330,
    "SZER.": 280,
    "GR.": 15,
    "SZT": 1,
    "MATERIAŁ": "PL. WIOROWA",
    "UWAGI": "BRW"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "2F RAMA [rys. 014]",
    "LP": 2,
    "NAZWA": "PŁ. TYŁ",
    "DŁ.": 1330,
    "SZER.": 35,
    "GR.": 15,
    "SZT": 1,
    "MATERIAŁ": "PL. WIOROWA",
    "UWAGI": "BRW"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "2F RAMA [rys. 014]",
    "LP": 3,
    "NAZWA": "PŁ. WEW. PRZÓD",
    "DŁ.": 580,
    "SZER.": 35,
    "GR.": 15,
    "SZT": 2,
    "MATERIAŁ": "PL. WIOROWA",
    "UWAGI": "BRW"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "2F RAMA [rys. 014]",
    "LP": 4,
    "NAZWA": "LIST. BOK",
    "DŁ.": 222,
    "SZER.": 50,
    "GR.": 47,
    "SZT": 2,
    "MATERIAŁ": "T-CA SOSNA",
    "UWAGI": "BRW"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "2F RAMA [rys. 014]",
    "LP": 5,
    "NAZWA": "LIST. TYŁ-PRZÓD",
    "DŁ.": 1330,
    "SZER.": 47,
    "GR.": 35,
    "SZT": 2,
    "MATERIAŁ": "T-CA SOSNA",
    "UWAGI": "016"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "2F RAMA [rys. 014]",
    "LP": 6,
    "NAZWA": "LIST. BOK",
    "DŁ.": 695,
    "SZER.": 47,
    "GR.": 35,
    "SZT": 2,
    "MATERIAŁ": "T-CA SOSNA",
    "UWAGI": "Z-019"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "2F RAMA [rys. 014]",
    "LP": 7,
    "NAZWA": "LIST. ŚR.",
    "DŁ.": 640,
    "SZER.": 47,
    "GR.": 35,
    "SZT": 1,
    "MATERIAŁ": "T-CA SOSNA",
    "UWAGI": "015"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "2F RAMA [rys. 014]",
    "LP": 8,
    "NAZWA": "LIST. DÓŁ PRZÓD",
    "DŁ.": 1330,
    "SZER.": 50,
    "GR.": 23,
    "SZT": 1,
    "MATERIAŁ": "T-CA SOSNA",
    "UWAGI": "Z-017"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "2F RAMA [rys. 014]",
    "LP": 9,
    "NAZWA": "LIST. WEW. PRZÓD",
    "DŁ.": 222,
    "SZER.": 50,
    "GR.": 23,
    "SZT": 2,
    "MATERIAŁ": "T-CA SOSNA",
    "UWAGI": "BRW"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "2F RAMA [rys. 014]",
    "LP": 10,
    "NAZWA": "KL. MONT.",
    "DŁ.": 50,
    "SZER.": 50,
    "GR.": 23,
    "SZT": 4,
    "MATERIAŁ": "T-CA SOSNA",
    "UWAGI": "BRW"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "2F RAMA [rys. 014]",
    "LP": 11,
    "NAZWA": "LIST. WEW. BOK",
    "DŁ.": 300,
    "SZER.": 35,
    "GR.": 20,
    "SZT": 2,
    "MATERIAŁ": "T-CA SOSNA",
    "UWAGI": "BRW"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "2F RAMA [rys. 014]",
    "LP": 12,
    "NAZWA": "LIST. TYŁ DÓŁ",
    "DŁ.": 1330,
    "SZER.": 23,
    "GR.": 20,
    "SZT": 1,
    "MATERIAŁ": "T-CA SOSNA",
    "UWAGI": "BRW"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "2F RAMA [rys. 014]",
    "LP": 13,
    "NAZWA": "LIST. BOK DÓŁ",
    "DŁ.": 635,
    "SZER.": 23,
    "GR.": 20,
    "SZT": 2,
    "MATERIAŁ": "T-CA SOSNA",
    "UWAGI": "BRW"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "2F RAMA [rys. 014]",
    "LP": 14,
    "NAZWA": "TAŚMA ZACZEP. 6SZT.",
    "DŁ.": 600,
    "SZT": 4,
    "MATERIAŁ": "TWORZYWO",
    "UWAGI": "BRW"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "2F RAMA [rys. 014]",
    "LP": 15,
    "NAZWA": "BL_KĄTOWA 70x70",
    "DŁ.": 70,
    "SZER.": 70,
    "GR.": 20,
    "SZT": 2,
    "MATERIAŁ": "STAL",
    "UWAGI": "BRW"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "2F RAMA [rys. 014]",
    "LP": 16,
    "NAZWA": "WKRET ST 3x30",
    "SZT": 17,
    "MATERIAŁ": "STAL",
    "UWAGI": "BRW"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "2F RAMA [rys. 014]",
    "LP": 17,
    "NAZWA": "NAK. KLOWA M8",
    "SZT": 2,
    "MATERIAŁ": "STAL",
    "UWAGI": "BRW"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "2F RAMA [rys. 014]",
    "LP": 18,
    "NAZWA": "NAK. KLOWA M6",
    "SZT": 4,
    "MATERIAŁ": "STAL",
    "UWAGI": "BRW"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "LC [rys. 017]",
    "LP": 1,
    "NAZWA": "PŁ. BOK",
    "DŁ.": 895,
    "SZER.": 640,
    "GR.": 15,
    "SZT": 2,
    "MATERIAŁ": "PL. WIOROWA",
    "UWAGI": "017.1"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "LC [rys. 017]",
    "LP": 2,
    "NAZWA": "PŁ. WEW. PRZ-TYŁ",
    "DŁ.": 700,
    "SZER.": 280,
    "GR.": 15,
    "SZT": 2,
    "MATERIAŁ": "PL. WIOROWA",
    "UWAGI": "BRW"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "LC [rys. 017]",
    "LP": 3,
    "NAZWA": "PŁ. PRZEG. WEW.",
    "DŁ.": 700,
    "SZER.": 256,
    "GR.": 15,
    "SZT": 1,
    "MATERIAŁ": "PL. WIOROWA",
    "UWAGI": "018"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "LC [rys. 017]",
    "LP": 4,
    "NAZWA": "LIST. SIED.",
    "DŁ.": 1290,
    "SZER.": 50,
    "GR.": 23,
    "SZT": 4,
    "MATERIAŁ": "T-CA SOSNA",
    "UWAGI": "BRW"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "LC [rys. 017]",
    "LP": 5,
    "NAZWA": "LIST. OPAR.",
    "DŁ.": 700,
    "SZER.": 50,
    "GR.": 23,
    "SZT": 5,
    "MATERIAŁ": "T-CA SOSNA",
    "UWAGI": "BRW"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "LC [rys. 017]",
    "LP": 6,
    "NAZWA": "LIST. WEW. PRZ. DOL.",
    "DŁ.": 600,
    "SZER.": 50,
    "GR.": 23,
    "SZT": 1,
    "MATERIAŁ": "T-CA SOSNA",
    "UWAGI": "BRW"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "LC [rys. 017]",
    "LP": 7,
    "NAZWA": "LIST. SIED. TYŁ KR.",
    "DŁ.": 400,
    "SZER.": 50,
    "GR.": 23,
    "SZT": 2,
    "MATERIAŁ": "T-CA SOSNA",
    "UWAGI": "BRW"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "LC [rys. 017]",
    "LP": 8,
    "NAZWA": "LIST. NAR. PRZÓD",
    "DŁ.": 150,
    "SZER.": 50,
    "GR.": 23,
    "SZT": 2,
    "MATERIAŁ": "T-CA SOSNA",
    "UWAGI": "BRW"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "LC [rys. 017]",
    "LP": 9,
    "NAZWA": "KL. MONT.",
    "DŁ.": 50,
    "SZER.": 50,
    "GR.": 23,
    "SZT": 12,
    "MATERIAŁ": "T-CA SOSNA",
    "UWAGI": "BRW"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "LC [rys. 017]",
    "LP": 10,
    "NAZWA": "LIST. WEW. SIED. PRZ-TYŁ",
    "DŁ.": 600,
    "SZER.": 25,
    "GR.": 25,
    "SZT": 2,
    "MATERIAŁ": "T-CA SOSNA",
    "UWAGI": "BRW"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "LC [rys. 017]",
    "LP": 11,
    "NAZWA": "PŁ. TYŁ OPAR.",
    "DŁ.": 730,
    "SZER.": 640,
    "GR.": 3,
    "SZT": 1,
    "MATERIAŁ": "PL. HDF",
    "UWAGI": "BRW"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "LC [rys. 017]",
    "LP": 12,
    "NAZWA": "PŁ. PRZÓD OPAR.",
    "DŁ.": 730,
    "SZER.": 300,
    "GR.": 3,
    "SZT": 1,
    "MATERIAŁ": "PL. HDF",
    "UWAGI": "BRW"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "LC [rys. 017]",
    "LP": 13,
    "NAZWA": "PŁ. BOK PRZÓD",
    "DŁ.": 595,
    "SZER.": 280,
    "GR.": 3,
    "SZT": 2,
    "MATERIAŁ": "PL. HDF",
    "UWAGI": "BRW"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "LC [rys. 017]",
    "LP": 14,
    "NAZWA": "PŁ. GÓR. OPAR.",
    "DŁ.": 730,
    "SZER.": 170,
    "GR.": 3,
    "SZT": 1,
    "MATERIAŁ": "PL. HDF",
    "UWAGI": "BRW"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "LC [rys. 017]",
    "LP": 15,
    "NAZWA": "TAŚMA ZACZEP. 12SZT.",
    "DŁ.": 1200,
    "SZT": 2,
    "MATERIAŁ": "TWORZYWO",
    "UWAGI": "BRW"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "LC [rys. 017]",
    "LP": 16,
    "NAZWA": "NAK. KLOWA M6",
    "SZT": 8,
    "MATERIAŁ": "STAL",
    "UWAGI": "BRW"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "PODŁOKIETNIK PRAWY [rys. 019]",
    "LP": 1,
    "NAZWA": "PŁ. BOK WEW.",
    "DŁ.": 910,
    "SZER.": 280,
    "GR.": 15,
    "SZT": 1,
    "MATERIAŁ": "PL. WIOROWA",
    "UWAGI": "020"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "PODŁOKIETNIK PRAWY [rys. 019]",
    "LP": 2,
    "NAZWA": "PŁ. PRZÓD-TYŁ",
    "DŁ.": 550,
    "SZER.": 175,
    "GR.": 15,
    "SZT": 2,
    "MATERIAŁ": "PL. WIOROWA",
    "UWAGI": "BRW"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "PODŁOKIETNIK PRAWY [rys. 019]",
    "LP": 5,
    "NAZWA": "LIST. WEW.",
    "DŁ.": 880,
    "SZER.": 50,
    "GR.": 23,
    "SZT": 5,
    "MATERIAŁ": "T-CA SOSNA",
    "UWAGI": "BRW"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "PODŁOKIETNIK PRAWY [rys. 019]",
    "LP": 4,
    "NAZWA": "LIST. DÓŁ",
    "DŁ.": 152,
    "SZER.": 50,
    "GR.": 23,
    "SZT": 3,
    "MATERIAŁ": "T-CA SOSNA",
    "UWAGI": "BRW"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "PODŁOKIETNIK PRAWY [rys. 019]",
    "LP": 5,
    "NAZWA": "LIST. GÓRA",
    "DŁ.": 175,
    "SZER.": 25,
    "GR.": 25,
    "SZT": 2,
    "MATERIAŁ": "T-CA SOSNA",
    "UWAGI": "BRW"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "PODŁOKIETNIK PRAWY [rys. 019]",
    "LP": 6,
    "NAZWA": "PŁ. GÓRA",
    "DŁ.": 910,
    "SZER.": 175,
    "GR.": 3,
    "SZT": 1,
    "MATERIAŁ": "PL. PILSNIOWA",
    "UWAGI": "BRW"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "PODŁOKIETNIK PRAWY [rys. 019]",
    "LP": 7,
    "NAZWA": "PŁ. DYST.",
    "DŁ.": 100,
    "SZER.": 15,
    "GR.": 6,
    "SZT": 6,
    "MATERIAŁ": "PL. MDF",
    "UWAGI": "BRW"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "PODŁOKIETNIK PRAWY [rys. 019]",
    "LP": 8,
    "NAZWA": "TEK. BOK ZEW.",
    "DŁ.": 910,
    "SZER.": 550,
    "GR.": 1,
    "SZT": 1,
    "MATERIAŁ": "TEKTURA",
    "UWAGI": "BRW"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "PODŁOKIETNIK PRAWY [rys. 019]",
    "LP": 9,
    "NAZWA": "TEK. BOK WEW.",
    "DŁ.": 910,
    "SZER.": 270,
    "GR.": 1,
    "SZT": 1,
    "MATERIAŁ": "TEKTURA",
    "UWAGI": "BRW"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "PODŁOKIETNIK PRAWY [rys. 019]",
    "LP": 10,
    "NAZWA": "NAK. KLOWA M8",
    "SZT": 3,
    "MATERIAŁ": "STAL",
    "UWAGI": "BRW"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "3F SKRZYNIA [rys. 021.1]",
    "LP": 1,
    "NAZWA": "PŁ. PRZÓD",
    "DŁ.": 1884,
    "SZER.": 218,
    "GR.": 16,
    "SZT": 1,
    "MATERIAŁ": "PL. WIOROWA BIALA",
    "UWAGI": "008"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "3F SKRZYNIA [rys. 021.1]",
    "LP": 2,
    "NAZWA": "PŁ. TYŁ",
    "DŁ.": 1884,
    "SZER.": 218,
    "GR.": 16,
    "SZT": 1,
    "MATERIAŁ": "PL. WIOROWA BIALA",
    "UWAGI": "022"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "3F SKRZYNIA [rys. 021.1]",
    "LP": 3,
    "NAZWA": "PŁ. BOK",
    "DŁ.": 615,
    "SZER.": 218,
    "GR.": 16,
    "SZT": 2,
    "MATERIAŁ": "PL. MDF BIALA",
    "UWAGI": "023"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "3F SKRZYNIA [rys. 021.1]",
    "LP": 4,
    "NAZWA": "LIST. GÓR. ŚR.",
    "DŁ.": 584,
    "SZER.": 50,
    "GR.": 23,
    "SZT": 1,
    "MATERIAŁ": "T-CA SOSNA",
    "UWAGI": "FAZA"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "3F SKRZYNIA [rys. 021.1]",
    "LP": 5,
    "NAZWA": "LIST. TYŁ",
    "DŁ.": 177,
    "SZER.": 50,
    "GR.": 23,
    "SZT": 1,
    "MATERIAŁ": "T-CA SOSNA",
    "UWAGI": "FAZA"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "3F SKRZYNIA [rys. 021.1]",
    "LP": 6,
    "NAZWA": "LIST. TYŁ",
    "DŁ.": 170,
    "SZER.": 50,
    "GR.": 23,
    "SZT": 2,
    "MATERIAŁ": "T-CA SOSNA",
    "UWAGI": "FAZA"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "3F SKRZYNIA [rys. 021.1]",
    "LP": 7,
    "NAZWA": "PŁ. WEW.",
    "DŁ.": 584,
    "SZER.": 50,
    "GR.": 18,
    "SZT": 1,
    "MATERIAŁ": "SKLEJKA",
    "UWAGI": "FAZA"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "3F SKRZYNIA [rys. 021.1]",
    "LP": 8,
    "NAZWA": "PŁ. BOK DÓŁ",
    "DŁ.": 584,
    "SZER.": 50,
    "GR.": 18,
    "SZT": 2,
    "MATERIAŁ": "SKLEJKA",
    "UWAGI": "FAZA"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "3F SKRZYNIA [rys. 021.1]",
    "LP": 9,
    "NAZWA": "PŁ. BOK PRZÓD",
    "DŁ.": 177,
    "SZER.": 50,
    "GR.": 18,
    "SZT": 1,
    "MATERIAŁ": "SKLEJKA",
    "UWAGI": "FAZA"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "3F SKRZYNIA [rys. 021.1]",
    "LP": 10,
    "NAZWA": "PŁ. BOK PRZÓD",
    "DŁ.": 115,
    "SZER.": 50,
    "GR.": 18,
    "SZT": 2,
    "MATERIAŁ": "SKLEJKA",
    "UWAGI": "FAZA"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "3F SKRZYNIA [rys. 021.1]",
    "LP": 11,
    "NAZWA": "PŁ. DNO",
    "DŁ.": 1916,
    "SZER.": 615,
    "GR.": 3,
    "SZT": 1,
    "MATERIAŁ": "PL. PILSN. BIALA",
    "UWAGI": "024"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "3F SKRZYNIA [rys. 021.1]",
    "LP": 12,
    "NAZWA": "NAK. KLOWA M6",
    "SZT": 12,
    "MATERIAŁ": "STAL",
    "UWAGI": "BRW"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "3F SKRZYNIA [rys. 021.1]",
    "LP": 13,
    "NAZWA": "NAK. KLOWA M8",
    "SZT": 6,
    "MATERIAŁ": "STAL",
    "UWAGI": "BRW"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "3F SKRZYNIA [rys. 021.1]",
    "LP": 14,
    "NAZWA": "WKRET ST 3x30",
    "SZT": 14,
    "MATERIAŁ": "STAL",
    "UWAGI": "BRW"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "3F OPARCIE [rys. 025]",
    "LP": 1,
    "NAZWA": "PL. OPARCIA",
    "DŁ.": 1910,
    "SZER.": 640,
    "GR.": 6,
    "SZT": 1,
    "MATERIAŁ": "PL. MDF",
    "UWAGI": "026"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "3F OPARCIE [rys. 025]",
    "LP": 2,
    "NAZWA": "LIST. WEW.",
    "DŁ.": 540,
    "SZER.": 60,
    "GR.": 23,
    "SZT": 2,
    "MATERIAŁ": "T-CA SOSNA",
    "UWAGI": "BRW"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "3F OPARCIE [rys. 025]",
    "LP": 3,
    "NAZWA": "LIST. GÓRA-DÓŁ",
    "DŁ.": 1910,
    "SZER.": 50,
    "GR.": 23,
    "SZT": 2,
    "MATERIAŁ": "T-CA SOSNA",
    "UWAGI": "BRW"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "3F OPARCIE [rys. 025]",
    "LP": 4,
    "NAZWA": "LIST. WEW.",
    "DŁ.": 540,
    "SZER.": 50,
    "GR.": 23,
    "SZT": 3,
    "MATERIAŁ": "T-CA SOSNA",
    "UWAGI": "BRW"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "3F OPARCIE [rys. 025]",
    "LP": 5,
    "NAZWA": "PŁ. PRZÓD",
    "DŁ.": 1910,
    "SZER.": 640,
    "GR.": 3,
    "SZT": 1,
    "MATERIAŁ": "PL. PILSNIOWA",
    "UWAGI": "BRW"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "3F OPARCIE [rys. 025]",
    "LP": 6,
    "NAZWA": "NAK. KLOWA M6",
    "SZT": 6,
    "MATERIAŁ": "STAL",
    "UWAGI": "BRW"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "3F RAMA [rys. 027]",
    "LP": 1,
    "NAZWA": "PŁ. PRZÓD",
    "DŁ.": 1900,
    "SZER.": 280,
    "GR.": 15,
    "SZT": 1,
    "MATERIAŁ": "PL. WIOROWA",
    "UWAGI": "BRW"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "3F RAMA [rys. 027]",
    "LP": 2,
    "NAZWA": "PŁ. TYŁ",
    "DŁ.": 1900,
    "SZER.": 35,
    "GR.": 15,
    "SZT": 1,
    "MATERIAŁ": "PL. WIOROWA",
    "UWAGI": "BRW"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "3F RAMA [rys. 027]",
    "LP": 3,
    "NAZWA": "PŁ. WEW. PRZÓD",
    "DŁ.": 550,
    "SZER.": 35,
    "GR.": 15,
    "SZT": 3,
    "MATERIAŁ": "PL. WIOROWA",
    "UWAGI": "BRW"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "3F RAMA [rys. 027]",
    "LP": 4,
    "NAZWA": "LIST. BOK",
    "DŁ.": 222,
    "SZER.": 50,
    "GR.": 47,
    "SZT": 2,
    "MATERIAŁ": "T-CA SOSNA",
    "UWAGI": "BRW"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "3F RAMA [rys. 027]",
    "LP": 5,
    "NAZWA": "LIST. TYŁ-PRZÓD",
    "DŁ.": 1900,
    "SZER.": 47,
    "GR.": 35,
    "SZT": 2,
    "MATERIAŁ": "T-CA SOSNA",
    "UWAGI": "028"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "3F RAMA [rys. 027]",
    "LP": 6,
    "NAZWA": "LIST. BOK",
    "DŁ.": 695,
    "SZER.": 47,
    "GR.": 35,
    "SZT": 2,
    "MATERIAŁ": "T-CA SOSNA",
    "UWAGI": "029"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "3F RAMA [rys. 027]",
    "LP": 7,
    "NAZWA": "LIST. WEW.",
    "DŁ.": 640,
    "SZER.": 47,
    "GR.": 35,
    "SZT": 2,
    "MATERIAŁ": "T-CA SOSNA",
    "UWAGI": "030"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "3F RAMA [rys. 027]",
    "LP": 8,
    "NAZWA": "LIST. DÓŁ PRZÓD",
    "DŁ.": 1900,
    "SZER.": 50,
    "GR.": 23,
    "SZT": 1,
    "MATERIAŁ": "T-CA SOSNA",
    "UWAGI": "Z-017"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "3F RAMA [rys. 027]",
    "LP": 9,
    "NAZWA": "LIST. WEW. PRZÓD",
    "DŁ.": 222,
    "SZER.": 50,
    "GR.": 23,
    "SZT": 2,
    "MATERIAŁ": "T-CA SOSNA",
    "UWAGI": "BRW"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "3F RAMA [rys. 027]",
    "LP": 10,
    "NAZWA": "KL. MONT.",
    "DŁ.": 50,
    "SZER.": 50,
    "GR.": 23,
    "SZT": 4,
    "MATERIAŁ": "T-CA SOSNA",
    "UWAGI": "BRW"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "3F RAMA [rys. 027]",
    "LP": 11,
    "NAZWA": "LIST. WEW. BOK",
    "DŁ.": 250,
    "SZER.": 35,
    "GR.": 20,
    "SZT": 2,
    "MATERIAŁ": "T-CA SOSNA",
    "UWAGI": "BRW"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "3F RAMA [rys. 027]",
    "LP": 12,
    "NAZWA": "LIST. TYŁ DÓŁ",
    "DŁ.": 1900,
    "SZER.": 23,
    "GR.": 20,
    "SZT": 1,
    "MATERIAŁ": "T-CA SOSNA",
    "UWAGI": "BRW"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "3F RAMA [rys. 027]",
    "LP": 13,
    "NAZWA": "LIST. BOK DÓŁ",
    "DŁ.": 635,
    "SZER.": 23,
    "GR.": 20,
    "SZT": 2,
    "MATERIAŁ": "T-CA SOSNA",
    "UWAGI": "BRW"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "3F RAMA [rys. 027]",
    "LP": 14,
    "NAZWA": "TAŚMA ZACZEP. 6SZT.",
    "DŁ.": 600,
    "SZT": 2,
    "MATERIAŁ": "TWORZYWO",
    "UWAGI": "BRW"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "3F RAMA [rys. 027]",
    "LP": 15,
    "NAZWA": "TAŚMA ZACZEP. 5SZT.",
    "DŁ.": 500,
    "SZT": 4,
    "MATERIAŁ": "TWORZYWO",
    "UWAGI": "BRW"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "3F RAMA [rys. 027]",
    "LP": 16,
    "NAZWA": "BL_KĄTOWA 70x70",
    "DŁ.": 70,
    "SZER.": 70,
    "GR.": 20,
    "SZT": 2,
    "MATERIAŁ": "STAL",
    "UWAGI": "BRW"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "3F RAMA [rys. 027]",
    "LP": 17,
    "NAZWA": "WKRET ST 3x30",
    "SZT": 19,
    "MATERIAŁ": "STAL",
    "UWAGI": "BRW"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "3F RAMA [rys. 027]",
    "LP": 18,
    "NAZWA": "NAK. KLOWA M8",
    "SZT": 2,
    "MATERIAŁ": "STAL",
    "UWAGI": "BRW"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "3F RAMA [rys. 027]",
    "LP": 19,
    "NAZWA": "NAK. KLOWA M6",
    "SZT": 4,
    "MATERIAŁ": "STAL",
    "UWAGI": "BRW"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "PODŁOKIETNIK PRAWY I LEWY [rys. 019]",
    "LP": 1,
    "NAZWA": "PŁ. BOK WEW.",
    "DŁ.": 910,
    "SZER.": 280,
    "GR.": 15,
    "SZT": 2,
    "MATERIAŁ": "PL. WIOROWA",
    "UWAGI": "020"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "PODŁOKIETNIK PRAWY I LEWY [rys. 019]",
    "LP": 2,
    "NAZWA": "PŁ. PRZÓD-TYŁ",
    "DŁ.": 550,
    "SZER.": 175,
    "GR.": 15,
    "SZT": 4,
    "MATERIAŁ": "PL. WIOROWA",
    "UWAGI": "BRW"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "PODŁOKIETNIK PRAWY I LEWY [rys. 019]",
    "LP": 5,
    "NAZWA": "LIST. WEW.",
    "DŁ.": 880,
    "SZER.": 50,
    "GR.": 23,
    "SZT": 10,
    "MATERIAŁ": "T-CA SOSNA",
    "UWAGI": "BRW"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "PODŁOKIETNIK PRAWY I LEWY [rys. 019]",
    "LP": 4,
    "NAZWA": "LIST. DÓŁ",
    "DŁ.": 152,
    "SZER.": 50,
    "GR.": 23,
    "SZT": 6,
    "MATERIAŁ": "T-CA SOSNA",
    "UWAGI": "BRW"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "PODŁOKIETNIK PRAWY I LEWY [rys. 019]",
    "LP": 5,
    "NAZWA": "LIST. GÓRA",
    "DŁ.": 175,
    "SZER.": 25,
    "GR.": 25,
    "SZT": 4,
    "MATERIAŁ": "T-CA SOSNA",
    "UWAGI": "BRW"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "PODŁOKIETNIK PRAWY I LEWY [rys. 019]",
    "LP": 6,
    "NAZWA": "PŁ. GÓRA",
    "DŁ.": 910,
    "SZER.": 175,
    "GR.": 3,
    "SZT": 2,
    "MATERIAŁ": "PL. PILSNIOWA",
    "UWAGI": "BRW"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "PODŁOKIETNIK PRAWY I LEWY [rys. 019]",
    "LP": 7,
    "NAZWA": "PŁ. DYST.",
    "DŁ.": 100,
    "SZER.": 15,
    "GR.": 6,
    "SZT": 12,
    "MATERIAŁ": "PL. MDF",
    "UWAGI": "BRW"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "PODŁOKIETNIK PRAWY I LEWY [rys. 019]",
    "LP": 8,
    "NAZWA": "TEK. BOK ZEW.",
    "DŁ.": 910,
    "SZER.": 550,
    "GR.": 1,
    "SZT": 2,
    "MATERIAŁ": "TEKTURA",
    "UWAGI": "BRW"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "PODŁOKIETNIK PRAWY I LEWY [rys. 019]",
    "LP": 9,
    "NAZWA": "TEK. BOK WEW.",
    "DŁ.": 910,
    "SZER.": 270,
    "GR.": 1,
    "SZT": 2,
    "MATERIAŁ": "TEKTURA",
    "UWAGI": "BRW"
  },
  {
    "MODEL": "LIVY",
    "PODZESPÓŁ": "PODŁOKIETNIK PRAWY I LEWY [rys. 019]",
    "LP": 10,
    "NAZWA": "NAK. KLOWA M8",
    "SZT": 6,
    "MATERIAŁ": "STAL",
    "UWAGI": "BRW"
  }
]`;

const jsCode = convertJsonToJs(jsonData);
console.log(jsCode);
